export const subscriptionsMock = [
  {
    plan: "Basic plan",
    price: "$0",
    structure: "Free, no commitments here",
    values: [
      "Limited video courses",
      "Limited coding exercises",
      "Soft skill class",
      "DevX AI",
    ],
    action: "Try basic plan",
    discount: "",
    id: "1",
  },
  {
    plan: "Pro plan",
    price: "$99.99",
    structure: "Pay once every month",
    values: [
      "Access to 935+ video lectures",
      "Access to 515+ coding exercises",
      "Community of 300+ learners, grads and mentors",
      "Certificate of Completion",
    ],
    action: "Subscribe to pro",
    discount: "",
    id: "2",
  },
  {
    plan: "Premium plan",
    price: "$199.99",
    structure: "Pay once every month",
    values: [
      "2 hours of weekly live Group mentorship sessions",
      "Weekly feedback on interview question & answer video submission by mentors",
      "Career guidance: 1 CV review, 1 mock interview",
    ],
    action: "Choose premium",
    discount: "",
    id: "3",
  },
  {
    plan: "Basic plan",
    price: "$0",
    structure: "Free, no commitments here",
    values: [
      "Limited video courses",
      "Limited coding exercises",
      "Soft skill class",
      "DevX AI",
    ],
    action: "Try basic plan",
    discount: "",
    id: "4",
  },
  {
    plan: "Pro plan",
    price: "$296.00",
    structure: "Pay once every 3 months",
    values: [
      "Access to 935+ video lectures",
      "Access to 515+ coding exercises",
      "Community of 300+ learners, grads and mentors",
      "Certificate of Completion",
    ],
    action: "Subscribe to pro",
    discount: "Save 15%",
    id: "5",
  },
  {
    plan: "Premium plan",
    price: "$199.99",
    structure: "Pay once every month",
    values: [
      "2 hours of weekly live Group mentorship sessions",
      "Weekly feedback on interview question & answer video submission by mentors",
      "Career guidance: 1 CV review, 1 mock interview",
    ],
    action: "Choose premium",
    discount: "Save 22%",
    id: "6",
  },
];
